# Generated by Django 4.1.2 on 2022-10-20 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='star',
            field=models.BooleanField(default=False),
        ),
    ]
