# Generated by Django 4.1.1 on 2022-10-09 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0002_remove_movie_gv_url_movie_gv_id_alter_movie_genre"),
    ]

    operations = [
        migrations.RenameField(
            model_name="author",
            old_name="name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="author",
            name="last_name",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
