# Generated by Django 4.1.1 on 2022-10-09 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0004_remove_movie_genre_remove_movie_gv_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="purchase_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="grade",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="about.grade",
            ),
        ),
    ]
